---
kind: pipeline
type: docker
name: yig

clone:
  git:
    image: plugins/git

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/src/yig

steps:
- name: build & test
  image: centos-yig
  commands:
  - make build_internal

trigger:
  event:
  - push
